export default {
  START_FETCH: "START_FETCH",
  FINISH_FETCH: "FINISH_FETCH",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_FAIL: "FETCH_FAIL",
  ORDER_CARD: "ORDER_CARD",
  CHANGE_NAME: "CHANGE_NAME",
  VALID_NAME: "VALID_NAME",
  CHECKED_NAME: "CHECKED_NAME",
  CHANGE_PHONE: "CHANGE_PHONE",
  VALID_PHONE: "VALID_PHONE",
  CHECKED_PHONE: "CHECKED_PHONE",
}
